//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Changes&gt;
        ///  &lt;Change&gt;
        ///    &lt;dateTimeChange&gt;15.07.2022 15:06:18&lt;/dateTimeChange&gt;
        ///    &lt;dataChanged&gt;Поле 1&lt;/dataChanged&gt;
        ///    &lt;typeOfChanges&gt;Изменение&lt;/typeOfChanges&gt;
        ///    &lt;changer&gt;Андрей 1&lt;/changer&gt;
        ///  &lt;/Change&gt;
        ///  &lt;Change&gt;
        ///    &lt;dateTimeChange&gt;15.07.2022 15:06:18&lt;/dateTimeChange&gt;
        ///    &lt;dataChanged&gt;Поле 2&lt;/dataChanged&gt;
        ///    &lt;typeOfChanges&gt;Изменение&lt;/typeOfChanges&gt;
        ///    &lt;changer&gt;Андрей 2&lt;/changer&gt;
        ///  &lt;/Change&gt;
        ///  &lt;Change&gt;
        ///    &lt;dateTimeChange&gt;15.07.2022 15:06:18&lt;/dateTi [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Changes_log {
            get {
                return ResourceManager.GetString("Changes_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Persons&gt;
        ///  &lt;Person&gt;
        ///    &lt;id&gt;1&lt;/id&gt;
        ///    &lt;surname&gt;Ахвердов 1&lt;/surname&gt;
        ///    &lt;name&gt;Андрей 1&lt;/name&gt;
        ///    &lt;middleName&gt;Александрович 1&lt;/middleName&gt;
        ///    &lt;telephoneNumber&gt;89187669371&lt;/telephoneNumber&gt;
        ///    &lt;pasport&gt;0708 100501&lt;/pasport&gt;
        ///  &lt;/Person&gt;
        ///  &lt;Person&gt;
        ///    &lt;id&gt;2&lt;/id&gt;
        ///    &lt;surname&gt;Ахвердов 2&lt;/surname&gt;
        ///    &lt;name&gt;Андрей 2&lt;/name&gt;
        ///    &lt;middleName&gt;Александрович 2&lt;/middleName&gt;
        ///    &lt;telephoneNumber&gt;89187669372&lt;/telephoneNumber&gt;
        ///    &lt;pasport&gt;0708 100502&lt;/pasport&gt;
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Databook {
            get {
                return ResourceManager.GetString("Databook", resourceCulture);
            }
        }
    }
}
